import React, { useState } from 'react';
import {
  Upload,
  FileText,
  X,
  Gift,
  Users,
  Sparkles,
  BrainCircuit,
  CheckCircle2,
  ChevronDown,
  ClipboardList,
  MessageSquare,
  BarChart3,
  Loader2,
  PlusCircle,
  FlaskConical,
  AlertTriangle,
  Eye,
  Send,
  Inbox,
  ChevronRight,
  ChevronLeft,
  UserCheck,
  UserX,
  TrendingUp,
  ArrowLeft,
  Briefcase,
  Clock,
  Shuffle,
} from 'lucide-react';
import { UserRole, InterviewQuestion, UploadedFile, CvCandidate, Vacancy } from '../types';

interface VacanciesProps {
  activeRole: UserRole;
}

// ── MOCK VACANCIES LIST ──

const MOCK_VACANCIES: Vacancy[] = [
  { id: 'v1', title: 'Senior Backend Engineer', team: 'Platform Engineering', status: 'screening', createdAt: '12 Mar 2026', applicants: 6, approved: 3, rejected: 3 },
  { id: 'v2', title: 'Frontend Lead', team: 'Product & Growth', status: 'generated', createdAt: '8 Mar 2026', applicants: 0, approved: 0, rejected: 0 },
  { id: 'v3', title: 'Data Engineer', team: 'Data & AI Systems', status: 'draft', createdAt: '15 Mar 2026', applicants: 0, approved: 0, rejected: 0 },
  { id: 'v4', title: 'DevOps / SRE Engineer', team: 'Infrastructure & SRE', status: 'interviewing', createdAt: '1 Mar 2026', applicants: 8, approved: 2, rejected: 6 },
  { id: 'v5', title: 'QA Automation Engineer', team: 'Platform Engineering', status: 'completed', createdAt: '20 Feb 2026', applicants: 5, approved: 1, rejected: 4 },
];

const VACANCY_STATUS_CONFIG: Record<Vacancy['status'], { label: string; color: string; bg: string }> = {
  draft: { label: 'Borrador', color: 'text-outline', bg: 'bg-surface-container-high' },
  generated: { label: 'JD Generada', color: 'text-primary-container', bg: 'bg-primary-container/10' },
  screening: { label: 'Screening CVs', color: 'text-amber-600', bg: 'bg-amber-500/10' },
  interviewing: { label: 'Entrevistas', color: 'text-secondary', bg: 'bg-secondary/10' },
  completed: { label: 'Completada', color: 'text-secondary', bg: 'bg-secondary/10' },
};

// ── MOCK DATA ──

// Base template shown in "JD Generada" step (generic, pre-candidate)
const MOCK_BASE_QUESTIONS: InterviewQuestion[] = [
  { id: '1', category: 'Technical Architecture', question: '¿Cómo diseñarías un sistema de colas para procesar 10M de eventos por segundo?', expectedAnswer: 'Debería mencionar message brokers (Kafka/RabbitMQ), particionamiento, backpressure, idempotencia y estrategias de retry con dead-letter queues.', candidateAnswer: '' },
  { id: '2', category: 'Problem Solving', question: '¿Describe una situación donde tuviste que refactorizar un sistema legacy crítico. ¿Qué estrategia usaste?', expectedAnswer: 'Buscar mención de strangler fig pattern, feature flags, pruebas de regresión exhaustivas, migración gradual y comunicación con stakeholders.', candidateAnswer: '' },
  { id: '3', category: 'Team Collaboration', question: '¿Cómo manejas desacuerdos técnicos con otros seniors del equipo?', expectedAnswer: 'Evidencia de debate basado en datos, prototipos/POCs para validar ideas, capacidad de ceder cuando hay mejor evidencia, y documentación de decisiones (ADRs).', candidateAnswer: '' },
  { id: '4', category: 'DevOps & Infrastructure', question: '¿Qué estrategia de CI/CD implementarías para un equipo de 15 desarrolladores?', expectedAnswer: 'Trunk-based development o GitFlow según contexto, pipelines con stages (lint, test, build, deploy), ambientes de staging, canary/blue-green deployments.', candidateAnswer: '' },
];

// Personalized questions per candidate — generated by matching JD vs CV
const MOCK_PERSONALIZED_QUESTIONS: Record<string, InterviewQuestion[]> = {
  cv1: [
    {
      id: '1', category: 'Leadership at Scale',
      question: 'En MercadoLibre lideraste equipos de 6+ personas. ¿Cómo estructuraste los code reviews para mantener calidad sin convertirte en cuello de botella?',
      expectedAnswer: 'Proceso asíncrono con SLAs de revisión, ownership por área técnica, checklist automatizado (linters, tests) y cultura de feedback constructivo. Posiblemente menciona pair programming para transferencia de conocimiento.',
      candidateAnswer: '',
      tailoredFor: 'Liderazgo técnico confirmado en CV — el puesto requiere liderar un equipo de 8',
    },
    {
      id: '2', category: 'Distributed Systems Depth',
      question: 'Dado tu manejo de Kafka a escala, describe cómo garantizarías consistencia eventual en un sistema con múltiples consumidores procesando pagos del mismo topic.',
      expectedAnswer: 'Idempotencia en consumidores, exactly-once semantics o al-menos-una-vez con manejo de duplicados, sagas para transacciones distribuidas, y compensating transactions.',
      candidateAnswer: '',
      tailoredFor: 'Kafka y event-driven listado como fortaleza clave — validar profundidad real',
    },
    {
      id: '3', category: 'Technical Decision Making',
      question: '¿Cuál fue la decisión arquitectónica más controversial que tomaste en tu equipo? ¿Cómo convenciste a los stakeholders y qué resultó?',
      expectedAnswer: 'Proceso estructurado: data-driven, prototipo/POC, análisis de trade-offs documentado (ADR), presentación a stakeholders con riesgos explícitos. Resultado medible.',
      candidateAnswer: '',
      tailoredFor: 'Alto match técnico — explorar capacidad de influencia organizacional',
    },
    {
      id: '4', category: 'Infrastructure Optimization',
      question: '¿Cuál ha sido el reto de Kubernetes más complejo que resolviste en GCP? ¿Cómo optimizaste costos sin sacrificar SLOs?',
      expectedAnswer: 'Node autoscaling, spot/preemptible nodes, resource requests/limits bien calibrados, VPA/HPA, namespace quotas, y monitoring granular de costos por servicio.',
      candidateAnswer: '',
      tailoredFor: 'Kubernetes a escala es fortaleza del CV — el puesto requiere colaborar con SRE en costos',
    },
  ],
  cv2: [
    {
      id: '1', category: 'PostgreSQL Deep Dive',
      question: 'Con tu experiencia en sharding de PostgreSQL en Rappi, ¿cómo migrarías una base de datos de 500GB sin downtime? ¿Qué estrategia de rollback tendrías?',
      expectedAnswer: 'Blue-green para base de datos, logical replication para sync en caliente, migration scripts idempotentes, feature flags para cambiar write path, monitoreo de lag de replicación.',
      candidateAnswer: '',
      tailoredFor: 'PostgreSQL avanzado y sharding es su principal fortaleza según CV',
    },
    {
      id: '2', category: 'Infrastructure as Code',
      question: 'Vemos que tu experiencia con Terraform es limitada. Nuestro equipo lo usa intensivamente con GCP. ¿Cuál es tu nivel actual y cómo planeas cerrar esa brecha?',
      expectedAnswer: 'Honestidad sobre el nivel actual, plan concreto de aprendizaje, mencionar experiencia con herramientas similares (Pulumi, CDK, scripts Bash/Python), y disposición a pair con el equipo de SRE.',
      candidateAnswer: '',
      tailoredFor: 'Gap identificado en el screening: poca experiencia con Terraform — skill crítico del equipo',
    },
    {
      id: '3', category: 'API Design & gRPC',
      question: 'Como Backend Lead en Rappi manejando alto tráfico, ¿cómo diseñaste contratos gRPC entre servicios y cómo gestionaste breaking changes sin afectar a los consumers?',
      expectedAnswer: 'Buf para linting de .proto, versionado de packages, backward compatibility como regla, deprecation notices, consumer-driven contract testing, y rolling upgrades coordinados.',
      candidateAnswer: '',
      tailoredFor: 'gRPC y protobuf listado como fortaleza — validar manejo de API versioning a escala',
    },
    {
      id: '4', category: 'Mentorship & Growth',
      question: 'Describes la mentoría de juniors como fortaleza. ¿Cómo estructurarías un plan de desarrollo para un developer junior que quiere especializarse en sistemas distribuidos en los próximos 6 meses?',
      expectedAnswer: 'Plan con objetivos SMART, lecturas recomendadas (DDIA, etc.), proyectos progresivos con scope acotado, pair programming semanal, revisión de métricas de progreso, y ownership gradual de componentes.',
      candidateAnswer: '',
      tailoredFor: 'El puesto requiere mentoría activa del equipo junior — el CV lo menciona explícitamente',
    },
  ],
  cv3: [
    {
      id: '1', category: 'Gap: Orquestación',
      question: 'Tu CV muestra fuerte experiencia en Go y event-driven, pero no hemos visto Kubernetes en producción. ¿Cuál es tu nivel actual y qué tan rápido podrías operar de forma autónoma con K8s?',
      expectedAnswer: 'Nivel honesto (Docker, conceptos básicos, etc.), plan de cierre de brecha, mención de experiencia con herramientas relacionadas, y ejemplos de adopción rápida de nuevas tecnologías en el pasado.',
      candidateAnswer: '',
      tailoredFor: 'Gap crítico identificado en screening: sin experiencia directa con Kubernetes',
    },
    {
      id: '2', category: 'Event Sourcing Depth',
      question: 'Con CQRS y Event Sourcing en Nubank, ¿cómo manejarías la reconstrucción de un read model cuando hay 10M de eventos acumulados y un nuevo microservicio necesita arrancar?',
      expectedAnswer: 'Snapshots periódicos, proyecciones paralelas con checkpointing, partición por aggregate ID para procesamiento concurrente, y mecanismo de warm-up gradual para no saturar el event store.',
      candidateAnswer: '',
      tailoredFor: 'Event Sourcing y CQRS son su fortaleza principal — profundizar en casos extremos',
    },
    {
      id: '3', category: 'Leadership Without Title',
      question: 'El puesto requiere liderazgo técnico formal, pero tu historial no muestra ese rol. ¿Puedes describir situaciones donde influyiste en decisiones técnicas del equipo o actúaste como referente?',
      expectedAnswer: 'Ejemplos concretos de RFC internos, propuestas técnicas aceptadas, mentoría informal, presencia en design reviews, o liderazgo de proyectos cross-equipo sin reporte jerárquico.',
      candidateAnswer: '',
      tailoredFor: 'Gap identificado: sin liderazgo formal — rol requiere liderazgo técnico del equipo',
    },
    {
      id: '4', category: 'Testing Strategy',
      question: 'Tu cultura de testing fuerte es un activo valioso. ¿Cómo plantearías una estrategia de testing para microservicios Go con dependencias externas como Kafka, Redis y PostgreSQL?',
      expectedAnswer: 'Unit tests con mocks para dependencias externas, integration tests con testcontainers, contract testing para APIs gRPC, pruebas de chaos para resiliencia, y pipeline de CI que falla rápido.',
      candidateAnswer: '',
      tailoredFor: 'Testing fuerte es fortaleza clave — validar aplicación a arquitecturas distribuidas',
    },
  ],
};

// Mock answers per candidate for mock mode (candidateId → questionId → answer)
const MOCK_PERSONALIZED_ANSWERS: Record<string, Record<string, string>> = {
  cv1: {
    '1': 'En MercadoLibre establecimos un proceso de revisión asíncrono con SLA de 24 horas. Dividimos ownership por dominio técnico para que los reviews fueran entre expertos del área, no solo yo. Usamos Danger para checks automáticos y un checklist de arquitectura en PRs críticos.',
    '2': 'Usamos Kafka con particionamiento por merchant ID y consumidores idempotentes que verificaban en Redis si el evento ya fue procesado. Para transacciones de pago implementamos el patrón saga con compensating transactions y un servicio de reconciliación nocturno.',
    '3': 'Propuse migrar de REST a gRPC para los servicios internos. Hice un ADR completo con benchmarks, un POC en el servicio de menor riesgo, y una presentación ejecutiva mostrando la reducción de latencia del 40%. El CTO lo aprobó y lo rollamos en 4 sprints.',
    '4': 'Implementamos cluster autoscaler con node pools separados para workloads críticos y no críticos. Usamos spot instances para batch jobs, calibramos resource requests con VPA y logramos reducir costos de GKE un 35% sin tocar los SLOs.',
  },
  cv2: {
    '1': 'En Rappi migramos con Flyway y replicación lógica de PostgreSQL. Creamos la nueva estructura en paralelo, sincronizamos datos en tiempo real, y usamos un feature flag para cambiar el write path. El cutover completo fue en una ventana de mantenimiento de 2 minutos.',
    '2': 'Conozco los conceptos de Terraform y he hecho scripts básicos. Mi experiencia es más con infraestructura programática en Python y Bash. Me comprometo a completar la certificación de HashiCorp en los primeros 3 meses y hacer pair programming con el equipo de SRE.',
    '3': 'Usamos Buf Schema Registry para versionar los .proto. La regla era nunca hacer breaking changes en el mismo major version. Cuando necesitábamos cambios incompatibles, deprecábamos el campo antiguo por 2 sprints antes de eliminarlo y usábamos consumer-driven tests.',
    '4': 'Con cada junior hacía una sesión inicial para entender sus objetivos. Les asignaba issues de complejidad media con checklist detallado, hacíamos pair programming los viernes, y mensualmente revisábamos el progreso con métricas concretas: PRs merged, código en producción, incidentes resueltos.',
  },
  cv3: {
    '1': 'Mi nivel actual con Kubernetes es conceptual y de lab. He trabajado con Docker Compose en producción y entiendo los conceptos de pods, deployments y services. En Nubank usábamos una plataforma interna sobre K8s. Creo que en 4-6 semanas podría ser autónomo con soporte del equipo de SRE.',
    '2': 'Usábamos snapshots cada 1000 eventos con compresión. Para el warm-up de nuevos servicios procesábamos el snapshot primero y luego los eventos incrementales en paralelo usando goroutines con un pool de workers. El tiempo de arranque pasó de 45 minutos a 3 minutos.',
    '3': 'Propuse e implementé la migración del sistema de auditoría a Event Sourcing. Escribí el RFC, presenté los trade-offs al equipo, hice el prototipo y lideré la implementación aunque no era el tech lead. También mentoricé a 2 developers junior informalmente durante 6 meses.',
    '4': 'Usamos testcontainers para levantar PostgreSQL, Redis y Kafka en los integration tests. Para unit tests mocks de las interfaces. Tenemos una regla de cobertura mínima del 80% para paths críticos y los tests de integración corren en CI con ambientes efímeros en Docker.',
  },
};

const MOCK_GENERATED_JD = {
  title: 'Senior Backend Engineer',
  summary: 'Buscamos un Senior Backend Engineer para liderar la evolución de nuestros sistemas distribuidos de alta escala. El candidato ideal arquitectará microservicios robustos, mentorizará al equipo junior y definirá el roadmap técnico del motor de procesamiento core.',
  skills: ['Go / Rust', 'Kubernetes', 'PostgreSQL', 'gRPC', 'CI/CD', 'System Design'],
  responsibilities: [
    'Diseñar y mantener microservicios de alta concurrencia.',
    'Liderar code reviews y establecer estándares arquitectónicos.',
    'Colaborar con SRE para optimizar costos de infraestructura.',
    'Definir y monitorear SLOs para servicios críticos.',
  ],
  benefits: [
    'Trabajo 100% remoto con horario flexible',
    'Seguro de gastos médicos mayores y menores',
    'Vales de despensa y fondo de ahorro',
    'Presupuesto anual de capacitación ($2,000 USD)',
    '20 días de vacaciones desde el primer año',
  ],
};

const MOCK_TEAM_SUMMARY = `El equipo trabaja con microservicios en Go y gRPC, usa Kubernetes en GCP para orquestación, practica trunk-based development con CI/CD en GitHub Actions. Sprint reviews cada 2 semanas con planning trimestral. Necesitan alguien que lidere la migración a event-driven architecture. Stack: Go, PostgreSQL, Redis, Kafka, Terraform.`;

const MOCK_FILES: UploadedFile[] = [
  { name: 'JD_Senior_Backend_Engineer.pdf', size: '245.3 KB', type: 'pdf' },
  { name: 'Skills_Matrix_Platform_Team.pdf', size: '128.7 KB', type: 'pdf' },
];

const MOCK_BENEFITS = `- Trabajo 100% remoto con horario flexible\n- Seguro de gastos médicos mayores y menores\n- Vales de despensa y fondo de ahorro\n- Presupuesto anual de capacitación ($2,000 USD)\n- 20 días de vacaciones desde el primer año\n- Bonos trimestrales por desempeño`;

const MOCK_CV_CANDIDATES: CvCandidate[] = [
  { id: 'cv1', name: 'Diana Torres', matchScore: 91, status: 'approved', currentRole: 'Senior Backend Engineer @ MercadoLibre', experience: '7 años en sistemas distribuidos', strengths: ['Go y microservicios en producción', 'Kubernetes a escala', 'Experiencia con Kafka y event-driven', 'Liderazgo técnico de equipos de 6+'], gaps: [], feedback: '' },
  { id: 'cv2', name: 'Andrés Salazar', matchScore: 84, status: 'approved', currentRole: 'Backend Lead @ Rappi', experience: '6 años en backend de alto tráfico', strengths: ['PostgreSQL avanzado y sharding', 'CI/CD con GitHub Actions', 'gRPC y protobuf', 'Mentoría de juniors'], gaps: ['Poca experiencia con Terraform'], feedback: '' },
  { id: 'cv3', name: 'Valentina Rojas', matchScore: 76, status: 'approved', currentRole: 'Software Engineer III @ Nubank', experience: '5 años en fintech con Go', strengths: ['Go en producción 4 años', 'Event sourcing y CQRS', 'Cultura de testing fuerte'], gaps: ['Sin experiencia directa con Kubernetes', 'No ha liderado equipos formalmente'], feedback: '' },
  { id: 'cv4', name: 'Roberto Vega', matchScore: 38, status: 'rejected', currentRole: 'PHP Developer @ Agencia Web', experience: '4 años en desarrollo web', strengths: ['Buena actitud y ganas de aprender', 'Experiencia con Laravel'], gaps: ['Sin experiencia en sistemas distribuidos', 'No conoce Kubernetes ni contenedores', 'Experiencia limitada a monolitos PHP'], feedback: 'El candidato tiene buena actitud y capacidad de aprendizaje, pero su experiencia técnica está centrada en monolitos PHP y no cuenta con las bases necesarias en sistemas distribuidos, orquestación de contenedores ni message brokers que el puesto requiere.', crossMatchVacancy: 'Frontend Lead' },
  { id: 'cv5', name: 'Laura Méndez', matchScore: 45, status: 'rejected', currentRole: 'Backend Developer @ Startup', experience: '3 años en backend con Go', strengths: ['Conocimiento básico de Go', 'Familiaridad con PostgreSQL'], gaps: ['CI/CD limitado a deploys manuales', 'Sin experiencia con event-driven architecture', 'No ha trabajado a escala'], feedback: 'La candidata demuestra conocimiento en backend con Go, pero su experiencia en CI/CD se limita a scripts manuales y no ha trabajado con arquitecturas event-driven ni a la escala requerida.' },
  { id: 'cv6', name: 'Pedro Castillo', matchScore: 22, status: 'rejected', currentRole: 'Junior Frontend Developer', experience: '1.5 años en frontend con React', strengths: ['Motivación para transicionar a backend'], gaps: ['Sin experiencia en backend', 'No conoce Go ni lenguajes de sistemas', 'Sin conocimiento de infraestructura cloud'], feedback: 'El candidato es desarrollador frontend junior sin experiencia en backend ni infraestructura cloud. El perfil no se alinea con los requisitos del puesto.', crossMatchVacancy: 'Frontend Lead' },
];

const MOCK_CANDIDATE_ANSWERS: Record<string, string> = {
  '1': 'Implementaría Kafka como message broker con particionamiento por tenant ID, usando consumer groups para escalar horizontalmente. Aplicaría backpressure con rate limiting y tendría dead-letter queues para mensajes fallidos con retry exponencial.',
  '2': 'En mi empresa anterior migré un monolito de pagos usando strangler fig pattern. Empecé por las rutas de menor riesgo, usé feature flags para rollback seguro y mantuve ambos sistemas en paralelo 3 meses con tests de regresión automatizados.',
  '3': 'Prefiero proponer un POC rápido cuando hay desacuerdo técnico. En mi equipo anterior documentábamos las decisiones en ADRs y votábamos basándonos en datos de performance y mantenibilidad, no en opiniones.',
  '4': 'Implementaría trunk-based development con feature flags, pipelines de CI con lint/test/build paralelos, deploy automático a staging y canary releases a producción con rollback automático si las métricas caen.',
};

// ── HM TECHNICAL INTERVIEW QUESTIONS ──

const MOCK_HM_QUESTIONS: Record<string, InterviewQuestion[]> = {
  cv1: [
    { id: '1', category: 'Incident Response', question: 'Lunes 9am. Un alert llega: el servicio de pagos está al 95% de CPU y el p99 pasó de 200ms a 4 segundos. No hay deploy reciente. Walk me through tus primeros 10 minutos de diagnóstico.', expectedAnswer: 'Revisar dashboards de Grafana (goroutines, GC, connection pool), tail de logs buscando panics o timeouts, pprof en el pod para flame graph, verificar traffic spike en load balancer. Decisión rápida: rollback o hotfix.', candidateAnswer: '', tailoredFor: 'El equipo tiene on-call rotations — necesitamos saber cómo reaccionas bajo presión real' },
    { id: '2', category: 'Go Deep Dive', question: 'Tenemos un consumer de Kafka en Go que después de 6 horas de funcionamiento empieza a acumular memoria y se reinicia con OOM cada 30 minutos. ¿Cómo lo diagnosticarías y reproduces el problema?', expectedAnswer: 'Exponer /debug/pprof, heap profile antes/después de 30 min, buscar crecimiento lineal. Goroutine trace para detectar leaks. Reproducir localmente con mismo volumen + race detector. Sospecha: closures capturando referencias en canales o goroutines no terminadas.', candidateAnswer: '', tailoredFor: 'Kafka consumer es parte core del stack del equipo — validar manejo de memoria en Go' },
    { id: '3', category: 'Architecture Debate', question: 'Alguien del equipo propone usar Redis Streams en lugar de Kafka para los eventos internos, argumentando simplicidad. Tú crees que es un error. ¿Cómo llevas esa conversación?', expectedAnswer: 'ADR formal, spike de 3 días comparando: Kafka tiene replay nativo, consumer groups, retención durable configurable. Redis Streams pierde ordering bajo failover y no tiene exactly-once. Proponer experimento en servicio no crítico para decidir con datos.', candidateAnswer: '', tailoredFor: 'El equipo toma decisiones arquitectónicas colectivas — queremos ver cómo argumentas sin imponer' },
    { id: '4', category: 'Team Unblock', question: '2 engineers llevan 2 días bloqueados por un desacuerdo: uno quiere GraphQL, otro REST para la nueva API de catálogo. El planning es mañana. ¿Cómo lo resuelves hoy?', expectedAnswer: 'Sesión de 60 min con criterios técnicos objetivos: latencia, overhead de desarrollo, clientes que consumirán la API, flexibilidad futura. Cada uno defiende 15 min con datos. Si empatan, el tech lead decide y documenta. No dejar que la parálisis ate el sprint.', candidateAnswer: '', tailoredFor: 'Rol requiere liderazgo técnico y desbloqueo del equipo — situación real del día a día' },
  ],
  cv2: [
    { id: '1', category: 'PostgreSQL en Producción', question: 'Una query de reporting que analiza órdenes de los últimos 90 días tarda 12 segundos. EXPLAIN muestra un seq scan en una tabla de 50M rows. ¿Cuál es tu diagnosis y plan sin afectar producción?', expectedAnswer: 'EXPLAIN ANALYZE para ver el plan real. Índice en columna de fecha si no existe (CREATE INDEX CONCURRENTLY). Revisar statistics con VACUUM ANALYZE. Verificar table bloat. Si es reporting, considerar read replica o tabla de pre-agregados con actualización programada.', candidateAnswer: '', tailoredFor: 'PostgreSQL avanzado es su fortaleza — queremos ver su profundidad real en casos de producción' },
    { id: '2', category: 'CI/CD Optimization', question: 'Nuestro pipeline de GitHub Actions tarda 28 minutos. El paso de `go test ./...` toma 18 de esos. ¿Cómo lo atacas? ¿Qué cambiarías en los primeros 2 días?', expectedAnswer: 'Caché de módulos Go con cache-from. Separar tests unitarios (rápidos, en PR) de integración (scheduled job). Matrix de paralelización en GitHub Actions por packages. Identificar tests lentos con go test -v -json y optimizar o extraer. Objetivo: bajar a menos de 8 minutos.', candidateAnswer: '', tailoredFor: 'CI/CD con GitHub Actions es fortaleza del CV — el pipeline actual es un pain point real del equipo' },
    { id: '3', category: 'On-call Reality', question: 'Son las 2am. El servicio de checkout devuelve 503 al 30% de los requests. SRE te escala. ¿Cuál es tu runbook mental para los primeros 5 minutos?', expectedAnswer: '1) Health checks de pods 2) Rate de errors por endpoint en APM 3) Logs última hora (connection refused, timeouts) 4) Deploy reciente que se haya pasado 5) Si es DB, active connections y slow queries 6) Circuit breaker si el problema es downstream. Comunicar en canal de incident con updates cada 10 min.', candidateAnswer: '', tailoredFor: 'Backend Lead debe manejar incidentes — queremos su proceso mental real bajo presión' },
    { id: '4', category: 'Terraform Ramp-up', question: 'Tu primera semana: necesitas añadir un nuevo Cloud Run service con variables de Secret Manager a la infra Terraform existente. ¿Cómo lo abordas sin experiencia previa en Terraform?', expectedAnswer: 'Sesión de pair de 2h con un SRE para entender la estructura modular del repo. Leer la documentación de los recursos google_cloud_run_service y google_secret_manager_secret_iam_member. Clonar un módulo similar y adaptar. No hacer push sin code review de alguien del equipo las primeras 2 semanas.', candidateAnswer: '', tailoredFor: 'Gap: Terraform — el equipo lo usa intensivamente, queremos ver si puede rampearse rápido' },
  ],
  cv3: [
    { id: '1', category: 'Kubernetes Pragmático', question: 'Uno de nuestros pods se está evictando frecuentemente en horas pico. El nodo está al 90% de memoria. Kubernetes no es tu stack principal — ¿cuál es tu proceso de razonamiento para diagnosticarlo?', expectedAnswer: 'kubectl describe pod para ver el motivo de eviction. kubectl top nodes/pods para ver consumo real vs limits. Si el pod no tiene memory limits configurados, ese sería el primer fix. Si los tiene y se desborda, revisar con pprof si hay memory leak en el proceso. El proceso de debug es el mismo independientemente del orquestador.', candidateAnswer: '', tailoredFor: 'Gap crítico: sin experiencia directa con K8s — queremos ver su razonamiento, no el conocimiento memorizado' },
    { id: '2', category: 'Event Sourcing Real', question: 'Tenemos aggregates con 50K eventos por cuenta activa. Rebuilding el estado tarda 8 segundos. Sin snapshotting implementado, ¿cómo lo resuelves sin un rewrite completo?', expectedAnswer: 'Snapshots periódicos: serializar estado completo cada N eventos (1000 como heurística inicial) y guardar con el número de evento como checkpoint. Al rebuildar: cargar último snapshot + procesar solo eventos posteriores. Para cuentas existentes, migración lazy: snapshot al primer acceso. Métricas para validar mejora.', candidateAnswer: '', tailoredFor: 'Event Sourcing es su fortaleza clave — caso práctico real del sistema que van a tocar' },
    { id: '3', category: 'Code Review Leadership', question: 'Recibes para review un PR de 1200 líneas que refactoriza el dominio de inventario. Sin tests nuevos. El autor es un senior con 4 años en la empresa. ¿Cómo abordas el review y la conversación?', expectedAnswer: 'Entender el cambio a alto nivel primero. El tamaño y la falta de tests son señales de alarma independientemente del seniority. Feedback estructurado en el PR (no Slack). Señalar que cualquier refactor crítico necesita tests de regresión. Ofrecer pair para escribirlos. Si hay pushback, escalar al tech lead con los argumentos documentados.', candidateAnswer: '', tailoredFor: 'Sin liderazgo formal — queremos ver cómo ejerce influencia técnica con pares más senior' },
    { id: '4', category: 'Cambio Cultural', question: 'Notas que el equipo tiene un patrón de error swallowing en Go: `if err != nil { _ = err }` en servicios críticos. No eres el tech lead. ¿Cómo cambiarías esa práctica?', expectedAnswer: 'Documentar el patrón con ejemplos concretos del codebase y casos reales de fallos silenciosos. Llevarlo como item técnico a la retro o al siguiente tech sync. Hacer un PR modelo en un servicio no crítico mostrando el patrón correcto con métricas de errors caught. Proponer una regla de linter (errcheck) en el pipeline de CI. Cambiar cultura con ejemplos, no con reglas impuestas.', candidateAnswer: '', tailoredFor: 'Sin autoridad formal — probar capacidad de influencia lateral y mejora de calidad del equipo' },
  ],
};

const MOCK_HM_ANSWERS: Record<string, Record<string, string>> = {
  cv1: {
    '1': 'Primero abro Grafana: reviso goroutines activos, GC pause time y connection pool exhaustion. Luego hago tail de logs de la última hora buscando panics o connection refused. Si no hay nada obvio, accedo al pod con kubectl exec y corro pprof para el flame graph de CPU. Paralelamente verifico si hay traffic spike inusual en el load balancer o un scheduled job que corrió en ese momento. Con esa info decido si es rollback o hotfix.',
    '2': 'Sospecho goroutine leak. Expongo /debug/pprof en el pod y tomo un heap profile en el minuto 1 y otro a los 30 minutos. Si el heap crece linealmente hay un leak. Reviso el goroutine trace para ver cuáles se acumulan. Para reproducir localmente uso un benchmark con el mismo throughput de mensajes y activo el race detector. La causa más probable: closures en goroutines capturando referencias a buffers que no se liberan.',
    '3': 'Propongo un ADR formal con un spike de 3 días. Los criterios son objetivos: Kafka tiene replay nativo, consumer groups con offset management, retención durable y exactamente-una-vez con idempotencia. Redis Streams puede simular esto pero pierde ordering bajo failover y no tiene exactly-once garantizado. Propongo probar ambos en el servicio de notificaciones, que no es crítico, y dejar que los datos de latencia y confiabilidad decidan.',
    '4': 'Los llamo a los dos juntos ese mismo día para una sesión de 60 minutos. Pido que cada uno prepare 15 minutos defendiendo su approach con criterios concretos: latencia esperada, overhead de desarrollo, flexibilidad para evolucionar. Luego el equipo vota con esos criterios. Si empatan yo decido y lo documento en un ADR explicando el razonamiento. No podemos entrar al planning sin esta decisión tomada.',
  },
  cv2: {
    '1': 'Con EXPLAIN ANALYZE identifico si el seq scan tiene un filtro de fecha. Si la columna de fecha no tiene índice, creo uno con CREATE INDEX CONCURRENTLY para no bloquear la tabla. Si ya existe el índice, reviso si las estadísticas están actualizadas con VACUUM ANALYZE. Si la query es solo de reporting, la muevo a la read replica. Si hay table bloat lo verifico con pg_stat_user_tables y programo un VACUUM FULL en ventana de bajo tráfico.',
    '2': 'Día 1: activo caché de módulos Go en GitHub Actions con cache-from. Día 2: separo los tests en dos grupos: unitarios que corren en cada PR (target en menos de 5 min) e integración que van a un scheduled job. Para los tests Go uso go test -v -json | jq para identificar los 10 más lentos y los optimizo. Con matrix de paralelización puedo bajar de 18 a 4-6 minutos los tests unitarios.',
    '3': 'Primero reviso el dashboard del APM para ver qué endpoints tienen el 503 y si hay correlación temporal. Luego logs de la última hora buscando connection refused o database timeouts. Verifico si hubo algún deploy en las últimas 4 horas. Si el problema parece en la base de datos, reviso active connections con SELECT count(*) FROM pg_stat_activity. Comunico en el canal de incident cada 10 minutos aunque no tenga resolución todavía.',
    '4': 'Le pido a alguien de SRE una sesión de pair de 2 horas para entender la estructura modular del repo de Terraform antes de tocar nada. Leo la documentación de google_cloud_run_service y google_secret_manager_secret_iam_member. Clono el módulo de Cloud Run más similar al que necesito y adapto solo las variables. Todo mi código pasa por code review de alguien del equipo las primeras 2 semanas, sin excepción.',
  },
  cv3: {
    '1': 'Con kubectl describe pod veo el motivo exacto de eviction y si hay memory limits configurados. Con kubectl top pods veo el consumo real. Si no hay limits, ese es el primer fix: establecer requests y limits apropiados. Si los tiene y los desborda, el problema está en el proceso Go: uso pprof para verificar si hay memory leak. El proceso de debug es el mismo que en cualquier sistema: observar métricas, acotar el problema, actuar de lo más simple a lo más complejo.',
    '2': 'Implemento snapshotting periódico: cada 1000 eventos serializo el estado completo del aggregate y lo guardo en una tabla con el número de evento como checkpoint. Al rebuildar, cargo el último snapshot y proceso solo los eventos posteriores. En el peor caso proceso 999 eventos en lugar de 50K. Para los aggregates existentes hago la migración lazy: cuando se accede a uno por primera vez, genero el snapshot on-demand. Agrego métricas para validar la mejora.',
    '3': 'Primero entiendo el PR a alto nivel antes de revisar línea a línea. El tamaño y la falta de tests son señales de alarma que señalo en el review independientemente del seniority del autor. Dejo el feedback en el PR de forma constructiva: explico el por qué, no solo el qué. Ofrezco hacer un pair session para escribir los tests de regresión juntos. Si hay resistencia, escalo al tech lead con mis argumentos documentados.',
    '4': 'Primero recopilo ejemplos concretos del codebase donde el error swallowing causó o pudo causar un problema real. Los llevo como item técnico a la siguiente retro con evidencia. Hago un PR modelo en un servicio no crítico mostrando el patrón correcto, con el error logger apropiado. Propongo agregar errcheck como regla de linter en el pipeline de CI. No lo presento como "están haciendo mal", lo presento como "así podemos mejorar juntos".',
  },
};

// ── HR STEP DEFINITIONS ──

const HR_STEPS = [
  { key: 'input', label: 'JD & Beneficios' },
  { key: 'generated', label: 'JD Generada' },
  { key: 'screening', label: 'Screening CVs' },
  { key: 'interview', label: 'Entrevista RH' },
  { key: 'hm-interview', label: 'Entrevista HM' },
] as const;

type HrStep = typeof HR_STEPS[number]['key'];

// ── COMPONENT ──

export const Vacancies: React.FC<VacanciesProps> = ({ activeRole }) => {
  // Vacancy list vs detail
  const [selectedVacancy, setSelectedVacancy] = useState<string | null>(null);

  // Mock
  const [mockMode, setMockMode] = useState(false);

  // Wizard step (HR)
  const [currentStep, setCurrentStep] = useState<HrStep>('input');

  // Step 1: Inputs
  const [jdFiles, setJdFiles] = useState<UploadedFile[]>([]);
  const [companyBenefits, setCompanyBenefits] = useState('');
  const [teamContext, setTeamContext] = useState('Platform Engineering');
  const [roleType, setRoleType] = useState('Senior Backend Engineer');
  const [hmSubmitted, setHmSubmitted] = useState(false);

  // Step 2: Generated
  const [isGenerating, setIsGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);

  // Step 3: Screening
  const [cvCandidates, setCvCandidates] = useState<CvCandidate[]>([]);
  const [expandedCandidate, setExpandedCandidate] = useState<string | null>(null);

  // Step 4: HR Interview
  const [selectedCandidate, setSelectedCandidate] = useState<string | null>(null);
  const [questions, setQuestions] = useState<InterviewQuestion[]>(MOCK_BASE_QUESTIONS);
  const [matchScore, setMatchScore] = useState<number | null>(null);
  const [isEvaluating, setIsEvaluating] = useState(false);
  const [hrDecision, setHrDecision] = useState<'none' | 'continue' | 'reject'>('none');

  // Step 5: HM Technical Interview
  const [hmQuestions, setHmQuestions] = useState<InterviewQuestion[]>([]);
  const [hmMatchScore, setHmMatchScore] = useState<number | null>(null);
  const [isHmEvaluating, setIsHmEvaluating] = useState(false);

  const approvedCandidates = cvCandidates.filter((c) => c.status === 'approved');
  const rejectedCandidates = cvCandidates.filter((c) => c.status === 'rejected');
  const interviewCandidate = cvCandidates.find((c) => c.id === selectedCandidate);
  const answeredAll = questions.every((q) => q.candidateAnswer.trim().length > 0);
  const canGenerate = activeRole === 'hr' && (jdFiles.length > 0 || companyBenefits.trim().length > 0);

  const hmAnsweredAll = hmQuestions.every((q) => q.candidateAnswer.trim().length > 0);

  const resetVacancyState = () => {
    setCurrentStep('input');
    setJdFiles([]);
    setCompanyBenefits('');
    setGenerated(false);
    setCvCandidates([]);
    setSelectedCandidate(null);
    setMatchScore(null);
    setHrDecision('none');
    setHmQuestions([]);
    setHmMatchScore(null);
    setIsHmEvaluating(false);
    setHmSubmitted(false);
    setExpandedCandidate(null);
    setIsGenerating(false);
    setIsEvaluating(false);
    setQuestions(MOCK_BASE_QUESTIONS);
    setMockMode(false);
  };

  const toggleMockMode = () => {
    const next = !mockMode;
    setMockMode(next);
    if (next) {
      setJdFiles(MOCK_FILES);
      setCompanyBenefits(MOCK_BENEFITS);
      setTeamContext('Platform Engineering');
      setRoleType('Senior Backend Engineer');
      setHmSubmitted(true);
      setGenerated(true);
      setCvCandidates(MOCK_CV_CANDIDATES);
      // Pre-load HR + HM questions for the first approved candidate (cv1)
      const firstCandidateQs = MOCK_PERSONALIZED_QUESTIONS['cv1'] ?? MOCK_BASE_QUESTIONS;
      const firstAnswers = MOCK_PERSONALIZED_ANSWERS['cv1'] ?? {};
      setQuestions(firstCandidateQs.map((q) => ({ ...q, candidateAnswer: firstAnswers[q.id] ?? '' })));
      setSelectedCandidate('cv1');
      setHrDecision('continue');
      const hmQs = MOCK_HM_QUESTIONS['cv1'] ?? [];
      const hmAns = MOCK_HM_ANSWERS['cv1'] ?? {};
      setHmQuestions(hmQs.map((q) => ({ ...q, candidateAnswer: hmAns[q.id] ?? '' })));
    } else {
      resetVacancyState();
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files) return;
    const newFiles: UploadedFile[] = Array.from(files).map((f) => ({
      name: f.name,
      size: `${(f.size / 1024).toFixed(1)} KB`,
      type: f.name.endsWith('.pdf') ? 'pdf' : f.name.endsWith('.doc') || f.name.endsWith('.docx') ? 'doc' : 'other',
    }));
    setJdFiles((prev) => [...prev, ...newFiles]);
    e.target.value = '';
  };

  const removeFile = (index: number) => setJdFiles((prev) => prev.filter((_, i) => i !== index));

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      setGenerated(true);
      setCurrentStep('generated');
    }, 2000);
  };

  const handleShowScreening = () => {
    if (cvCandidates.length === 0) setCvCandidates(MOCK_CV_CANDIDATES);
    setCurrentStep('screening');
  };

  const handleSelectCandidate = (id: string) => {
    setSelectedCandidate(id);
    setMatchScore(null);
    setHrDecision('none');
    setHmMatchScore(null);
    setHmQuestions([]);
    const personalized = MOCK_PERSONALIZED_QUESTIONS[id] ?? MOCK_BASE_QUESTIONS;
    const answers = mockMode ? (MOCK_PERSONALIZED_ANSWERS[id] ?? {}) : {};
    setQuestions(personalized.map((q) => ({ ...q, candidateAnswer: answers[q.id] ?? '' })));
    setCurrentStep('interview');
  };

  const handleHrDecision = (decision: 'continue' | 'reject') => {
    setHrDecision(decision);
    if (decision === 'continue' && selectedCandidate) {
      const hmQs = MOCK_HM_QUESTIONS[selectedCandidate] ?? [];
      const hmAns = mockMode ? (MOCK_HM_ANSWERS[selectedCandidate] ?? {}) : {};
      setHmQuestions(hmQs.map((q) => ({ ...q, candidateAnswer: hmAns[q.id] ?? '' })));
      setCurrentStep('hm-interview');
    }
  };

  const handleHmCandidateAnswer = (id: string, answer: string) => {
    setHmQuestions((prev) => prev.map((q) => (q.id === id ? { ...q, candidateAnswer: answer } : q)));
  };

  const handleHmEvaluate = () => {
    setIsHmEvaluating(true);
    setTimeout(() => {
      setIsHmEvaluating(false);
      const answeredCount = hmQuestions.filter((q) => q.candidateAnswer.trim().length > 0).length;
      const base = answeredCount / hmQuestions.length;
      setHmMatchScore(Math.round(base * 88 + Math.random() * 12));
    }, 1800);
  };

  const handleCandidateAnswer = (id: string, answer: string) => {
    setQuestions((prev) => prev.map((q) => (q.id === id ? { ...q, candidateAnswer: answer } : q)));
  };

  const handleEvaluate = () => {
    setIsEvaluating(true);
    setTimeout(() => {
      setIsEvaluating(false);
      const answeredCount = questions.filter((q) => q.candidateAnswer.trim().length > 0).length;
      const base = answeredCount / questions.length;
      setMatchScore(Math.round(base * 85 + Math.random() * 15));
    }, 1800);
  };

  const handleOpenVacancy = (id: string) => {
    resetVacancyState();
    setSelectedVacancy(id);
  };

  const handleBackToList = () => {
    setSelectedVacancy(null);
    resetVacancyState();
  };

  // Determine which steps are accessible
  const stepEnabled = (key: HrStep): boolean => {
    switch (key) {
      case 'input': return true;
      case 'generated': return generated;
      case 'screening': return generated;
      case 'interview': return cvCandidates.length > 0 && approvedCandidates.length > 0;
      case 'hm-interview': return hrDecision === 'continue' && hmQuestions.length > 0;
    }
  };

  const currentStepIndex = HR_STEPS.findIndex((s) => s.key === currentStep);

  // ── VACANCY LIST VIEW ──
  if (!selectedVacancy) {
    return (
      <div className="p-8 max-w-7xl mx-auto">
        <header className="mb-10">
          <nav className="flex text-[11px] font-bold uppercase tracking-widest text-on-primary-container mb-2">
            <span className="opacity-50">Talent AI-Quisition</span>
            <span className="mx-2 opacity-50">/</span>
            <span>Vacancies</span>
          </nav>
          <div className="flex justify-between items-end">
            <div>
              <h2 className="font-headline text-4xl font-extrabold text-primary-container tracking-tight">Vacantes</h2>
              <p className="text-on-surface-variant mt-1">
                {activeRole === 'hr' ? 'Gestiona todas las vacantes abiertas y su progreso.' : 'Consulta el estado de las vacantes de tu equipo.'}
              </p>
            </div>
            <div className="flex items-center gap-2 px-4 py-2 bg-surface-container-low rounded-lg">
              <div className={`w-2 h-2 rounded-full ${activeRole === 'hr' ? 'bg-secondary' : 'bg-primary-container'}`} />
              <span className="text-xs font-bold text-on-surface-variant uppercase tracking-wider">
                {activeRole === 'hr' ? 'Recursos Humanos' : 'Hiring Manager'}
              </span>
            </div>
          </div>
        </header>

        {/* Stats bar */}
        <div className="grid grid-cols-4 gap-4 mb-8">
          {[
            { label: 'Total Vacantes', value: MOCK_VACANCIES.length, color: 'text-primary-container' },
            { label: 'En Screening', value: MOCK_VACANCIES.filter((v) => v.status === 'screening').length, color: 'text-amber-600' },
            { label: 'En Entrevistas', value: MOCK_VACANCIES.filter((v) => v.status === 'interviewing').length, color: 'text-secondary' },
            { label: 'Completadas', value: MOCK_VACANCIES.filter((v) => v.status === 'completed').length, color: 'text-secondary' },
          ].map((stat) => (
            <div key={stat.label} className="bg-surface-container-lowest p-5 rounded-2xl shadow-sm">
              <p className="text-[10px] font-black uppercase tracking-widest text-outline mb-1">{stat.label}</p>
              <p className={`font-headline text-3xl font-extrabold ${stat.color}`}>{stat.value}</p>
            </div>
          ))}
        </div>

        {/* Vacancy cards */}
        <div className="space-y-3">
          {MOCK_VACANCIES.map((v) => {
            const sc = VACANCY_STATUS_CONFIG[v.status];
            const stepNum = v.status === 'draft' ? 1 : v.status === 'generated' ? 2 : v.status === 'screening' ? 3 : v.status === 'interviewing' ? 3 : 4;
            return (
              <div key={v.id} onClick={() => handleOpenVacancy(v.id)} className="bg-surface-container-lowest p-6 rounded-2xl shadow-sm hover:shadow-md transition-all cursor-pointer group border border-transparent hover:border-secondary/20">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 bg-primary-container/10 rounded-xl flex items-center justify-center group-hover:bg-primary-container/20 transition-colors">
                      <Briefcase className="text-primary-container" size={22} />
                    </div>
                    <div>
                      <h3 className="text-base font-bold text-on-surface group-hover:text-primary-container transition-colors">{v.title}</h3>
                      <div className="flex items-center gap-3 mt-0.5">
                        <span className="text-xs text-on-surface-variant">{v.team}</span>
                        <span className="text-xs text-outline flex items-center gap-1"><Clock size={10} />{v.createdAt}</span>
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-6">
                    {v.applicants > 0 && (
                      <div className="text-right">
                        <p className="text-xs text-on-surface-variant">{v.applicants} aplicantes</p>
                        <p className="text-[10px] text-outline">{v.approved} aprobados · {v.rejected} rechazados</p>
                      </div>
                    )}
                    <div className="flex items-center gap-3">
                      {/* Progress dots */}
                      <div className="flex items-center gap-1">
                        {[1, 2, 3, 4].map((s) => (
                          <div key={s} className={`w-2 h-2 rounded-full ${s <= stepNum ? 'bg-secondary' : 'bg-surface-container-high'}`} />
                        ))}
                      </div>
                      <span className={`px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-wider ${sc.color} ${sc.bg}`}>{sc.label}</span>
                      <ChevronRight className="text-outline group-hover:text-secondary transition-colors" size={18} />
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    );
  }

  // ── VACANCY DETAIL (PAGINATED WIZARD) ──
  const vacancy = MOCK_VACANCIES.find((v) => v.id === selectedVacancy);

  return (
    <div className="p-8 max-w-7xl mx-auto">
      {/* Header */}
      <header className="mb-8">
        <div className="flex items-center gap-2 mb-4">
          <button onClick={handleBackToList} className="flex items-center gap-2 text-on-surface-variant hover:text-primary-container transition-colors text-sm font-bold">
            <ArrowLeft size={16} />Vacantes
          </button>
          <span className="text-outline mx-1">/</span>
          <span className="text-sm font-bold text-on-surface">{vacancy?.title}</span>
        </div>
        <div className="flex justify-between items-end">
          <div>
            <h2 className="font-headline text-3xl font-extrabold text-primary-container tracking-tight">{vacancy?.title}</h2>
            <p className="text-on-surface-variant mt-1 text-sm">{vacancy?.team}</p>
          </div>
          <div className="flex items-center gap-3">
            {activeRole === 'hr' && (
              <button onClick={toggleMockMode} className={`flex items-center gap-2 px-4 py-2 rounded-lg font-bold text-xs uppercase tracking-wider transition-all ${mockMode ? 'bg-amber-500 text-white shadow-md shadow-amber-500/25' : 'bg-surface-container-low text-on-surface-variant hover:bg-surface-container-high'}`}>
                <FlaskConical size={14} />Mock {mockMode ? 'ON' : 'OFF'}
              </button>
            )}
            <div className="flex items-center gap-2 px-4 py-2 bg-surface-container-low rounded-lg">
              <div className={`w-2 h-2 rounded-full ${activeRole === 'hr' ? 'bg-secondary' : 'bg-primary-container'}`} />
              <span className="text-xs font-bold text-on-surface-variant uppercase tracking-wider">
                {activeRole === 'hr' ? 'Recursos Humanos' : 'Hiring Manager'}
              </span>
            </div>
          </div>
        </div>
      </header>

      {/* ── STEP INDICATOR (clickable, paginated) ── */}
      {activeRole === 'hr' && (
        <div className="flex items-center gap-0 mb-10 bg-surface-container-lowest rounded-2xl p-2 shadow-sm">
          {HR_STEPS.map((s, i) => {
            const enabled = stepEnabled(s.key);
            const active = currentStep === s.key;
            const done = (s.key === 'input' && (jdFiles.length > 0 || companyBenefits.trim().length > 0))
              || (s.key === 'generated' && generated)
              || (s.key === 'screening' && cvCandidates.length > 0)
              || (s.key === 'interview' && matchScore !== null)
              || (s.key === 'hm-interview' && hmMatchScore !== null);
            return (
              <React.Fragment key={s.key}>
                <button
                  onClick={() => enabled && setCurrentStep(s.key)}
                  disabled={!enabled}
                  className={`flex-1 flex items-center justify-center gap-2 py-3 px-4 rounded-xl text-xs font-bold uppercase tracking-wider transition-all ${
                    active
                      ? 'bg-primary-container text-white shadow-md'
                      : enabled
                        ? 'text-on-surface-variant hover:bg-surface-container-low cursor-pointer'
                        : 'text-outline/40 cursor-not-allowed'
                  }`}
                >
                  <div className={`w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-black ${
                    active ? 'bg-white/20 text-white' : done ? 'bg-secondary text-white' : 'bg-surface-container-high text-outline'
                  }`}>
                    {done && !active ? <CheckCircle2 size={12} /> : i + 1}
                  </div>
                  {s.label}
                </button>
                {i < HR_STEPS.length - 1 && <div className="w-px h-8 bg-outline-variant/20" />}
              </React.Fragment>
            );
          })}
        </div>
      )}

      {/* HM: simplified view */}
      {activeRole === 'hiring_manager' && (
        <div className="flex items-center gap-4 p-5 bg-surface-container-low rounded-xl mb-8 border border-outline-variant/20">
          <div className="w-10 h-10 bg-surface-container-high rounded-lg flex items-center justify-center flex-shrink-0"><Send className="text-outline" size={18} /></div>
          <div>
            <p className="text-sm font-bold text-on-surface">Vista de Hiring Manager</p>
            <p className="text-xs text-on-surface-variant">Revisa los inputs y documentos de la vacante. RH gestiona el proceso de selección.</p>
          </div>
        </div>
      )}

      {/* ── PAGE CONTENT ── */}

      {/* STEP 1: INPUTS */}
      {(currentStep === 'input' || activeRole === 'hiring_manager') && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* JD Upload */}
          <section className="bg-surface-container-lowest p-8 rounded-2xl shadow-sm">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 bg-primary-container rounded-xl flex items-center justify-center"><FileText className="text-white" size={20} /></div>
              <div>
                <h3 className="font-headline text-lg font-bold text-on-surface">Job Description & Skills</h3>
                <p className="text-xs text-on-surface-variant">Sube la JD original y documentos de habilidades requeridas</p>
              </div>
            </div>
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="block text-[10px] font-black uppercase tracking-widest text-outline ml-1">Equipo</label>
                  <div className="relative">
                    <select value={teamContext} onChange={(e) => setTeamContext(e.target.value)} className="w-full bg-surface-container-low border-none rounded-lg p-3 text-sm font-semibold focus:ring-2 focus:ring-secondary transition-all appearance-none">
                      <option>Platform Engineering</option>
                      <option>Infrastructure & SRE</option>
                      <option>Product & Growth</option>
                      <option>Data & AI Systems</option>
                    </select>
                    <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 text-outline pointer-events-none" size={14} />
                  </div>
                </div>
                <div className="space-y-2">
                  <label className="block text-[10px] font-black uppercase tracking-widest text-outline ml-1">Rol</label>
                  <input value={roleType} onChange={(e) => setRoleType(e.target.value)} className="w-full bg-surface-container-low border-none rounded-lg p-3 text-sm font-semibold focus:ring-2 focus:ring-secondary transition-all" placeholder="e.g., Senior Backend Engineer" type="text" />
                </div>
              </div>
              <label className="flex flex-col items-center justify-center p-8 border-2 border-dashed border-outline-variant/40 rounded-xl cursor-pointer hover:border-secondary hover:bg-secondary/5 transition-all group">
                <Upload className="text-outline-variant group-hover:text-secondary mb-3 transition-colors" size={32} />
                <span className="text-sm font-bold text-on-surface-variant group-hover:text-secondary transition-colors">Arrastra archivos PDF o haz clic para subir</span>
                <span className="text-[10px] text-outline mt-1">Job Description, Skills Matrix</span>
                <input type="file" accept=".pdf,.doc,.docx" multiple className="hidden" onChange={handleFileUpload} />
              </label>
              {jdFiles.length > 0 && (
                <div className="space-y-2">
                  {jdFiles.map((file, i) => (
                    <div key={i} className="flex items-center justify-between p-3 bg-surface-container-low rounded-lg">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 bg-error-container rounded-lg flex items-center justify-center"><FileText className="text-on-error-container" size={16} /></div>
                        <div><p className="text-sm font-bold text-on-surface">{file.name}</p><p className="text-[10px] text-outline">{file.size}</p></div>
                      </div>
                      <button onClick={() => removeFile(i)} className="p-1 hover:bg-surface-container-high rounded transition-colors"><X className="text-outline" size={16} /></button>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </section>

          {/* Right panel: role-specific */}
          {activeRole === 'hr' ? (
            <section className="bg-surface-container-lowest p-8 rounded-2xl shadow-sm">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 bg-secondary rounded-xl flex items-center justify-center"><Gift className="text-white" size={20} /></div>
                <div>
                  <h3 className="font-headline text-lg font-bold text-on-surface">Beneficios de la Empresa</h3>
                  <p className="text-xs text-on-surface-variant">Se incluirán en la Job Description generada</p>
                </div>
              </div>
              <textarea value={companyBenefits} onChange={(e) => setCompanyBenefits(e.target.value)} className="w-full bg-surface-container-low border-none rounded-xl p-4 text-sm focus:ring-2 focus:ring-secondary transition-all resize-none" placeholder={"Ejemplo:\n- Trabajo remoto\n- Seguro de gastos médicos\n- Vales de despensa"} rows={6} />
              <div className="mt-4 p-4 bg-surface-container-low rounded-xl">
                <p className="text-[10px] font-black uppercase tracking-widest text-outline mb-3">Agregar rápido</p>
                <div className="flex flex-wrap gap-2">
                  {['Remoto', 'Híbrido', 'Seguro médico', 'Stock options', 'Capacitación', 'Bonos'].map((tag) => (
                    <button key={tag} onClick={() => setCompanyBenefits((prev) => prev + (prev ? '\n- ' : '- ') + tag)} className="px-3 py-1.5 bg-surface-container-lowest text-on-surface-variant text-[11px] font-bold rounded-lg border border-outline-variant/20 hover:border-secondary hover:text-secondary transition-all">
                      <PlusCircle className="inline mr-1" size={12} />{tag}
                    </button>
                  ))}
                </div>
              </div>
              <div className="mt-6 p-4 bg-primary-container/5 border border-primary-container/20 rounded-xl">
                <div className="flex items-center gap-2 mb-2">
                  <Users className="text-primary-container" size={16} />
                  <p className="text-[10px] font-black uppercase tracking-widest text-primary-container">Resumen de Team Inputs (Hiring Manager)</p>
                  {hmSubmitted ? <CheckCircle2 className="text-secondary ml-auto" size={14} /> : <AlertTriangle className="text-amber-500 ml-auto" size={14} />}
                </div>
                {hmSubmitted ? (
                  <p className="text-xs text-on-surface-variant leading-relaxed">{MOCK_TEAM_SUMMARY}</p>
                ) : (
                  <p className="text-xs text-amber-600 font-medium">El Hiring Manager aún no ha enviado los inputs del equipo.</p>
                )}
              </div>
            </section>
          ) : (
            <section className="bg-surface-container-lowest p-8 rounded-2xl shadow-sm">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 bg-secondary rounded-xl flex items-center justify-center"><Users className="text-white" size={20} /></div>
                <div>
                  <h3 className="font-headline text-lg font-bold text-on-surface">Resumen de Team Inputs</h3>
                  <p className="text-xs text-on-surface-variant">Resumen agregado de las actividades del equipo</p>
                </div>
              </div>
              {hmSubmitted ? (
                <>
                  <div className="p-4 bg-surface-container-low rounded-xl mb-4"><p className="text-sm text-on-surface leading-relaxed">{MOCK_TEAM_SUMMARY}</p></div>
                  <div className="flex items-center gap-2 text-secondary"><CheckCircle2 size={16} /><span className="text-xs font-bold">Inputs enviados a RH</span></div>
                </>
              ) : (
                <div className="p-8 border-2 border-dashed border-outline-variant/30 rounded-xl flex flex-col items-center justify-center text-center">
                  <Users className="text-outline-variant mb-3" size={32} />
                  <p className="text-sm font-bold text-on-surface-variant mb-1">Aún no se han recopilado los inputs</p>
                  <p className="text-xs text-outline">Ve al tab de "Team Inputs" para que cada miembro registre sus actividades.</p>
                </div>
              )}
              <div className="mt-6 p-4 bg-surface-container-low rounded-xl">
                <div className="flex items-center gap-2 mb-2"><Eye className="text-outline" size={14} /><p className="text-[10px] font-black uppercase tracking-widest text-outline">Tu rol en este paso</p></div>
                <p className="text-xs text-on-surface-variant leading-relaxed">Como Hiring Manager, asegúrate de que los inputs del equipo estén completos y la JD base cargada. RH gestionará el proceso.</p>
              </div>
            </section>
          )}
        </div>
      )}

      {/* STEP 2: GENERATED JD */}
      {currentStep === 'generated' && activeRole === 'hr' && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          <div className="lg:col-span-7 space-y-6">
            <div className="bg-surface-container-lowest p-8 rounded-2xl shadow-sm">
              <div className="flex justify-between items-start mb-6">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-secondary-container rounded-xl flex items-center justify-center"><BrainCircuit className="text-on-secondary-container" size={20} /></div>
                  <div>
                    <h3 className="font-headline text-xl font-bold text-on-surface">{MOCK_GENERATED_JD.title}</h3>
                    <p className="text-xs text-on-surface-variant">Job Description optimizada por IA</p>
                  </div>
                </div>
                <span className="px-3 py-1 bg-secondary-container text-on-secondary-container text-[10px] font-black uppercase tracking-widest rounded-full">AI Generated</span>
              </div>
              <p className="text-sm text-on-surface leading-relaxed mb-6">{MOCK_GENERATED_JD.summary}</p>
              <div className="grid grid-cols-2 gap-4 mb-6">
                <div className="p-4 bg-surface-container-low rounded-xl">
                  <h4 className="text-[10px] font-black uppercase tracking-widest text-outline mb-3">Skills Requeridas</h4>
                  <div className="flex flex-wrap gap-2">
                    {MOCK_GENERATED_JD.skills.map((skill) => (<span key={skill} className="px-3 py-1.5 bg-secondary-container text-on-secondary-container rounded-lg text-[11px] font-bold">{skill}</span>))}
                  </div>
                </div>
                <div className="p-4 bg-surface-container-low rounded-xl">
                  <h4 className="text-[10px] font-black uppercase tracking-widest text-outline mb-3">Equipo Destino</h4>
                  <p className="text-sm font-semibold text-primary-container">{teamContext}</p>
                  <p className="text-xs text-on-surface-variant mt-1">{roleType}</p>
                </div>
              </div>
              <div className="mb-6">
                <h4 className="text-[10px] font-black uppercase tracking-widest text-outline mb-3">Responsabilidades Clave</h4>
                <ul className="space-y-3">
                  {MOCK_GENERATED_JD.responsibilities.map((resp, i) => (
                    <li key={i} className="flex gap-3">
                      <span className="w-6 h-6 flex items-center justify-center bg-primary-container text-white text-[10px] font-bold rounded-full flex-shrink-0">0{i + 1}</span>
                      <p className="text-sm leading-snug">{resp}</p>
                    </li>
                  ))}
                </ul>
              </div>
              <div className="p-4 bg-secondary/5 border border-secondary/20 rounded-xl">
                <h4 className="text-[10px] font-black uppercase tracking-widest text-secondary mb-3"><Gift className="inline mr-1" size={12} />Beneficios Incluidos</h4>
                <ul className="space-y-1.5">
                  {MOCK_GENERATED_JD.benefits.map((b, i) => (<li key={i} className="flex items-center gap-2 text-sm text-on-surface"><CheckCircle2 className="text-secondary flex-shrink-0" size={14} />{b}</li>))}
                </ul>
              </div>
            </div>
          </div>
          <div className="lg:col-span-5 space-y-4">
            {/* Personalization notice */}
            <div className="flex items-start gap-3 p-4 bg-amber-500/10 border border-amber-500/20 rounded-xl">
              <Sparkles className="text-amber-600 flex-shrink-0 mt-0.5" size={16} />
              <div>
                <p className="text-xs font-bold text-amber-700">Preguntas se personalizarán por candidato</p>
                <p className="text-[11px] text-amber-600 leading-relaxed mt-0.5">
                  Al iniciar la entrevista de cada candidato, la IA cruzará su CV con esta JD y generará preguntas específicas que profundizan en sus fortalezas y sondean sus gaps.
                </p>
              </div>
            </div>

            <div className="bg-primary-container text-white p-8 rounded-2xl shadow-xl overflow-hidden relative">
              <div className="absolute top-0 right-0 w-32 h-32 bg-secondary opacity-20 blur-3xl -mr-10 -mt-10 rounded-full" />
              <div className="flex items-center gap-3 mb-6">
                <ClipboardList className="text-secondary" size={24} />
                <div>
                  <h3 className="font-headline text-xl font-bold">Plantilla Base de Preguntas</h3>
                  <p className="text-xs text-on-primary-container">Template generado de la JD — se adaptará a cada candidato</p>
                </div>
              </div>
              <div className="space-y-5">
                {MOCK_BASE_QUESTIONS.map((q, i) => (
                  <div key={q.id} className="border-b border-white/10 pb-4 last:border-0">
                    <p className="text-[10px] font-black uppercase text-on-primary-container tracking-widest mb-1">{q.category} — Q{i + 1}</p>
                    <p className="text-sm font-semibold mb-2">"{q.question}"</p>
                    <div className="p-3 bg-white/5 rounded-lg border-l-2 border-secondary">
                      <p className="text-[10px] text-on-primary-container uppercase font-bold mb-1">Respuesta esperada:</p>
                      <p className="text-xs italic opacity-80">{q.expectedAnswer}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* STEP 3: CV SCREENING */}
      {currentStep === 'screening' && activeRole === 'hr' && (
        <section>
          {cvCandidates.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-16 text-center">
              <Inbox className="text-outline-variant mb-4" size={48} />
              <p className="text-lg font-bold text-on-surface-variant mb-2">Esperando recepción de CVs</p>
              <p className="text-sm text-outline mb-6">Una vez publicada la vacante, los CVs se recibirán y evaluarán automáticamente por IA.</p>
              <button onClick={handleShowScreening} className="flex items-center gap-3 px-8 py-3 rounded-xl font-bold text-sm bg-primary-container text-white hover:opacity-90 transition-all shadow-lg">
                <Inbox size={18} />Simular recepción de CVs
              </button>
            </div>
          ) : (
            <>
              <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-primary-container rounded-xl flex items-center justify-center"><Inbox className="text-white" size={20} /></div>
                  <div>
                    <h3 className="font-headline text-2xl font-bold text-on-surface">Screening de CVs</h3>
                    <p className="text-sm text-on-surface-variant">Se recibieron {cvCandidates.length} CVs. La IA los evaluó automáticamente.</p>
                  </div>
                </div>
                <div className="flex gap-3">
                  <div className="flex items-center gap-2 px-3 py-1.5 bg-secondary/10 rounded-lg"><UserCheck className="text-secondary" size={14} /><span className="text-xs font-bold text-secondary">{approvedCandidates.length} Aprobados</span></div>
                  <div className="flex items-center gap-2 px-3 py-1.5 bg-error/10 rounded-lg"><UserX className="text-error" size={14} /><span className="text-xs font-bold text-error">{rejectedCandidates.length} Rechazados</span></div>
                </div>
              </div>

              {/* Approved */}
              <div className="mb-6">
                <p className="text-[10px] font-black uppercase tracking-widest text-secondary mb-3 ml-1">Candidatos Aprobados — Listos para Entrevista</p>
                <div className="space-y-3">
                  {approvedCandidates.map((c) => (
                    <div key={c.id} className="bg-surface-container-lowest rounded-2xl shadow-sm border-l-4 border-secondary overflow-hidden transition-all">
                      <div className="p-5 flex items-center justify-between cursor-pointer" onClick={() => setExpandedCandidate(expandedCandidate === c.id ? null : c.id)}>
                        <div className="flex items-center gap-4">
                          <div className="w-12 h-12 rounded-full bg-secondary-container flex items-center justify-center text-on-secondary-container text-sm font-black">{c.name.split(' ').map((n) => n[0]).join('')}</div>
                          <div>
                            <p className="text-sm font-bold text-on-surface">{c.name}</p>
                            <p className="text-xs text-on-surface-variant">{c.currentRole} · {c.experience}</p>
                          </div>
                        </div>
                        <div className="flex items-center gap-4">
                          <div className="text-right">
                            <p className="text-2xl font-headline font-black text-secondary">{c.matchScore}%</p>
                            <p className="text-[10px] font-bold text-secondary uppercase">Match</p>
                          </div>
                          <ChevronRight className={`text-outline transition-transform ${expandedCandidate === c.id ? 'rotate-90' : ''}`} size={18} />
                        </div>
                      </div>
                      {expandedCandidate === c.id && (
                        <div className="px-5 pb-5 pt-0 border-t border-outline-variant/10">
                          <div className="grid grid-cols-2 gap-4 mt-4">
                            <div>
                              <p className="text-[10px] font-black uppercase tracking-widest text-outline mb-2">Fortalezas</p>
                              <div className="space-y-1.5">{c.strengths.map((s, i) => (<div key={i} className="flex items-center gap-2 text-xs text-on-surface"><CheckCircle2 className="text-secondary flex-shrink-0" size={12} />{s}</div>))}</div>
                            </div>
                            {c.gaps.length > 0 && (
                              <div>
                                <p className="text-[10px] font-black uppercase tracking-widest text-outline mb-2">Áreas de mejora</p>
                                <div className="space-y-1.5">{c.gaps.map((g, i) => (<div key={i} className="flex items-center gap-2 text-xs text-on-surface-variant"><AlertTriangle className="text-amber-500 flex-shrink-0" size={12} />{g}</div>))}</div>
                              </div>
                            )}
                          </div>
                          <button onClick={() => handleSelectCandidate(c.id)} className="mt-4 flex items-center gap-2 px-6 py-2.5 rounded-lg font-bold text-sm bg-secondary text-white hover:opacity-90 transition-all">
                            <MessageSquare size={16} />Ir a Entrevista
                          </button>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              {/* Rejected */}
              <div>
                <p className="text-[10px] font-black uppercase tracking-widest text-error mb-3 ml-1">Candidatos Rechazados — Feedback de IA</p>
                <div className="space-y-3">
                  {rejectedCandidates.map((c) => (
                    <div key={c.id} className="bg-surface-container-lowest rounded-2xl shadow-sm border-l-4 border-error/40 overflow-hidden">
                      <div className="p-5 flex items-center justify-between cursor-pointer" onClick={() => setExpandedCandidate(expandedCandidate === c.id ? null : c.id)}>
                        <div className="flex items-center gap-4">
                          <div className="w-12 h-12 rounded-full bg-error-container flex items-center justify-center text-on-error-container text-sm font-black">{c.name.split(' ').map((n) => n[0]).join('')}</div>
                          <div>
                            <div className="flex items-center gap-2">
                              <p className="text-sm font-bold text-on-surface">{c.name}</p>
                              {c.crossMatchVacancy && (
                                <span className="flex items-center gap-1 px-2 py-0.5 bg-blue-500/10 text-blue-600 text-[10px] font-bold rounded-full border border-blue-500/20">
                                  <Shuffle size={10} />Fit: {c.crossMatchVacancy}
                                </span>
                              )}
                            </div>
                            <p className="text-xs text-on-surface-variant">{c.currentRole} · {c.experience}</p>
                          </div>
                        </div>
                        <div className="flex items-center gap-4">
                          <div className="text-right">
                            <p className="text-2xl font-headline font-black text-error">{c.matchScore}%</p>
                            <p className="text-[10px] font-bold text-error uppercase">No match</p>
                          </div>
                          <ChevronRight className={`text-outline transition-transform ${expandedCandidate === c.id ? 'rotate-90' : ''}`} size={18} />
                        </div>
                      </div>
                      {expandedCandidate === c.id && (
                        <div className="px-5 pb-5 pt-0 border-t border-outline-variant/10">
                          {c.crossMatchVacancy && (
                            <div className="mt-4 p-3 bg-blue-500/5 border border-blue-500/20 rounded-xl flex items-center gap-3">
                              <Shuffle className="text-blue-600 flex-shrink-0" size={16} />
                              <div>
                                <p className="text-xs font-bold text-blue-700">Posible match para otra vacante</p>
                                <p className="text-xs text-blue-600">La IA detectó que este candidato podría encajar en la posición de <span className="font-bold">{c.crossMatchVacancy}</span>.</p>
                              </div>
                            </div>
                          )}
                          <div className="mt-4 mb-4">
                            <p className="text-[10px] font-black uppercase tracking-widest text-outline mb-2">Gaps Identificados</p>
                            <div className="flex flex-wrap gap-2">
                              {c.gaps.map((gap, gi) => (<span key={gi} className="flex items-center gap-1 px-3 py-1.5 bg-error/5 text-error text-[11px] font-bold rounded-lg border border-error/20"><AlertTriangle size={12} />{gap}</span>))}
                            </div>
                          </div>
                          <div className="p-4 bg-surface-container-low rounded-xl">
                            <p className="text-[10px] font-black uppercase tracking-widest text-outline mb-2">Feedback para el candidato (generado por IA)</p>
                            <p className="text-sm text-on-surface leading-relaxed">{c.feedback}</p>
                          </div>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            </>
          )}
        </section>
      )}

      {/* STEP 4: INTERVIEW */}
      {currentStep === 'interview' && activeRole === 'hr' && (
        <section>
          {/* Candidate selector */}
          <div className="bg-surface-container-lowest p-5 rounded-2xl shadow-sm mb-6">
            <div className="flex items-center gap-3 mb-4">
              <UserCheck className="text-secondary" size={18} />
              <p className="text-xs font-black uppercase tracking-widest text-outline">Candidato seleccionado</p>
            </div>
            <div className="flex gap-3">
              {approvedCandidates.map((c) => (
                <button key={c.id} onClick={() => { if (selectedCandidate !== c.id) handleSelectCandidate(c.id); }} className={`flex items-center gap-3 px-4 py-3 rounded-xl transition-all ${selectedCandidate === c.id ? 'bg-secondary text-white shadow-md' : 'bg-surface-container-low text-on-surface-variant hover:bg-surface-container-high'}`}>
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center text-[10px] font-black ${selectedCandidate === c.id ? 'bg-white/20 text-white' : 'bg-secondary-container text-on-secondary-container'}`}>
                    {c.name.split(' ').map((n) => n[0]).join('')}
                  </div>
                  <div className="text-left">
                    <p className="text-sm font-bold">{c.name}</p>
                    <p className={`text-[10px] ${selectedCandidate === c.id ? 'text-white/70' : 'text-outline'}`}>CV: {c.matchScore}%</p>
                  </div>
                </button>
              ))}
            </div>
          </div>

          {interviewCandidate && (
            <>
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 bg-primary-container rounded-xl flex items-center justify-center"><MessageSquare className="text-white" size={20} /></div>
                <div>
                  <h3 className="font-headline text-2xl font-bold text-on-surface">Entrevista: {interviewCandidate.name}</h3>
                  <p className="text-sm text-on-surface-variant">{interviewCandidate.currentRole} · CV Score: {interviewCandidate.matchScore}%</p>
                </div>
              </div>

              {/* Personalization badge */}
              <div className="flex items-center gap-2 mb-4 px-1">
                <Sparkles className="text-amber-500" size={14} />
                <p className="text-xs font-bold text-amber-600 uppercase tracking-widest">Preguntas personalizadas por IA para {interviewCandidate.name}</p>
              </div>

              <div className="space-y-4">
                {questions.map((q, i) => (
                  <div key={q.id} className="bg-surface-container-lowest p-6 rounded-2xl shadow-sm">
                    <div className="flex items-start gap-4">
                      <span className="w-8 h-8 flex items-center justify-center bg-primary-container text-white text-xs font-bold rounded-lg flex-shrink-0">Q{i + 1}</span>
                      <div className="flex-1">
                        <div className="flex items-start justify-between gap-3 mb-1">
                          <p className="text-sm font-bold text-on-surface">{q.question}</p>
                        </div>
                        <p className="text-[10px] text-outline uppercase font-bold">{q.category}</p>
                        {q.tailoredFor && (
                          <div className="flex items-center gap-1.5 mt-1.5 mb-3">
                            <Shuffle className="text-blue-500 flex-shrink-0" size={11} />
                            <p className="text-[11px] text-blue-600 italic">{q.tailoredFor}</p>
                          </div>
                        )}
                        {!q.tailoredFor && <div className="mb-3" />}
                        <textarea value={q.candidateAnswer} onChange={(e) => handleCandidateAnswer(q.id, e.target.value)} className="w-full bg-surface-container-low border-none rounded-xl p-4 text-sm focus:ring-2 focus:ring-secondary transition-all resize-none" placeholder="Escribe la respuesta del candidato..." rows={3} />
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              <div className="flex justify-center mt-8">
                <button onClick={handleEvaluate} disabled={!answeredAll || isEvaluating} className={`flex items-center gap-3 px-10 py-4 rounded-xl font-black uppercase tracking-widest text-sm transition-all shadow-lg ${answeredAll && !isEvaluating ? 'bg-secondary text-white hover:opacity-90 cursor-pointer' : 'bg-surface-container-high text-outline cursor-not-allowed'}`}>
                  {isEvaluating ? (<><Loader2 className="animate-spin" size={20} />Evaluando con IA...</>) : (<><BarChart3 size={20} />Evaluar Match con IA</>)}
                </button>
              </div>

              {/* Match result */}
              {matchScore !== null && (
                <div className="mt-8 space-y-4">
                  <div className="bg-surface-container-lowest p-8 rounded-2xl shadow-lg">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-6">
                        <div className="relative w-28 h-28 flex items-center justify-center">
                          <svg className="w-full h-full transform -rotate-90">
                            <circle className="text-surface-container-high" cx="56" cy="56" fill="transparent" r="48" stroke="currentColor" strokeWidth="8" />
                            <circle className={matchScore >= 70 ? 'text-secondary' : 'text-error'} cx="56" cy="56" fill="transparent" r="48" stroke="currentColor" strokeDasharray="301" strokeDashoffset={301 - (301 * matchScore) / 100} strokeWidth="8" strokeLinecap="round" />
                          </svg>
                          <span className={`absolute font-headline font-black text-3xl ${matchScore >= 70 ? 'text-secondary' : 'text-error'}`}>{matchScore}%</span>
                        </div>
                        <div>
                          <h3 className="font-headline text-2xl font-bold text-on-surface">Resultado: {interviewCandidate.name}</h3>
                          <p className="text-xs text-on-surface-variant mb-1">CV Score: {interviewCandidate.matchScore}% → Entrevista RH: {matchScore}%</p>
                          <p className="text-sm text-on-surface-variant mt-1">
                            {matchScore >= 80 ? 'Excelente candidato. Altamente compatible.' : matchScore >= 60 ? 'Buen candidato con áreas de desarrollo.' : 'Necesita desarrollo significativo en áreas clave.'}
                          </p>
                        </div>
                      </div>
                      <div className="flex flex-col items-end gap-2">
                        <div className="flex items-center gap-2">
                          <CheckCircle2 className={matchScore >= 70 ? 'text-secondary' : 'text-error'} size={20} />
                          <span className={`text-sm font-bold ${matchScore >= 70 ? 'text-secondary' : 'text-error'}`}>
                            {matchScore >= 80 ? 'Recomendado' : matchScore >= 60 ? 'Considerar' : 'No recomendado'}
                          </span>
                        </div>
                        <div className="flex items-center gap-1 text-on-surface-variant">
                          <TrendingUp size={14} />
                          <span className="text-[10px] font-bold uppercase">Score combinado: {Math.round((interviewCandidate.matchScore + matchScore) / 2)}%</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* HR Decision */}
                  {hrDecision === 'none' && (
                    <div className="bg-surface-container-lowest p-6 rounded-2xl shadow-sm border border-outline-variant/20">
                      <p className="text-[10px] font-black uppercase tracking-widest text-outline mb-4">Decisión de RH — ¿Continúa el proceso?</p>
                      <div className="flex gap-4">
                        <button onClick={() => handleHrDecision('continue')} className="flex-1 flex items-center justify-center gap-3 py-4 rounded-xl font-bold text-sm bg-secondary text-white hover:opacity-90 transition-all shadow-lg cursor-pointer">
                          <CheckCircle2 size={20} />
                          Continuar → Hiring Manager
                        </button>
                        <button onClick={() => handleHrDecision('reject')} className="flex-1 flex items-center justify-center gap-3 py-4 rounded-xl font-bold text-sm bg-error/10 text-error border border-error/30 hover:bg-error/20 transition-all cursor-pointer">
                          <UserX size={20} />
                          Descartar Candidato
                        </button>
                      </div>
                    </div>
                  )}

                  {hrDecision === 'continue' && (
                    <div className="flex items-center gap-4 p-5 bg-secondary/10 border border-secondary/20 rounded-2xl">
                      <CheckCircle2 className="text-secondary flex-shrink-0" size={24} />
                      <div>
                        <p className="text-sm font-bold text-secondary">Candidato aprobado por RH</p>
                        <p className="text-xs text-on-surface-variant">Pasa a entrevista técnica con el Hiring Manager. Ve al paso siguiente para continuar.</p>
                      </div>
                    </div>
                  )}

                  {hrDecision === 'reject' && (
                    <div className="flex items-center gap-4 p-5 bg-error/10 border border-error/20 rounded-2xl">
                      <UserX className="text-error flex-shrink-0" size={24} />
                      <div>
                        <p className="text-sm font-bold text-error">Candidato descartado por RH</p>
                        <p className="text-xs text-on-surface-variant">El candidato no avanzará en el proceso. Puedes seleccionar otro candidato aprobado.</p>
                      </div>
                      <button onClick={() => setHrDecision('none')} className="ml-auto px-4 py-2 rounded-lg text-xs font-bold text-on-surface-variant hover:bg-surface-container-low transition-all">Cambiar decisión</button>
                    </div>
                  )}
                </div>
              )}
            </>
          )}
        </section>
      )}

      {/* STEP 5: HM TECHNICAL INTERVIEW */}
      {currentStep === 'hm-interview' && activeRole === 'hr' && interviewCandidate && (
        <section>
          {/* Context banner */}
          <div className="flex items-center gap-4 p-5 bg-primary-container/5 border border-primary-container/20 rounded-2xl mb-6">
            <div className="w-12 h-12 rounded-full bg-secondary-container flex items-center justify-center text-on-secondary-container text-sm font-black flex-shrink-0">
              {interviewCandidate.name.split(' ').map((n) => n[0]).join('')}
            </div>
            <div className="flex-1">
              <p className="text-sm font-bold text-on-surface">{interviewCandidate.name} — Aprobado por RH</p>
              <p className="text-xs text-on-surface-variant">CV: {interviewCandidate.matchScore}% · Entrevista RH: {matchScore}% · {interviewCandidate.currentRole}</p>
            </div>
            <div className="flex items-center gap-2 px-3 py-1.5 bg-secondary/10 rounded-lg">
              <CheckCircle2 className="text-secondary" size={14} />
              <span className="text-xs font-bold text-secondary">Aprobado por RH</span>
            </div>
          </div>

          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 bg-primary-container rounded-xl flex items-center justify-center">
              <Briefcase className="text-white" size={20} />
            </div>
            <div>
              <h3 className="font-headline text-2xl font-bold text-on-surface">Entrevista Técnica — Hiring Manager</h3>
              <p className="text-sm text-on-surface-variant">Preguntas de día a día reales, basadas en el stack y retos del equipo</p>
            </div>
          </div>

          <div className="flex items-center gap-2 mb-4 px-1">
            <Briefcase className="text-primary-container" size={14} />
            <p className="text-xs font-bold text-primary-container uppercase tracking-widest">Enfoque técnico real — Stack del equipo: Go · Kubernetes · PostgreSQL · Kafka</p>
          </div>

          <div className="space-y-4">
            {hmQuestions.map((q, i) => (
              <div key={q.id} className="bg-surface-container-lowest p-6 rounded-2xl shadow-sm">
                <div className="flex items-start gap-4">
                  <span className="w-8 h-8 flex items-center justify-center bg-primary-container text-white text-xs font-bold rounded-lg flex-shrink-0">T{i + 1}</span>
                  <div className="flex-1">
                    <p className="text-sm font-bold text-on-surface">{q.question}</p>
                    <p className="text-[10px] text-outline uppercase font-bold mt-1">{q.category}</p>
                    {q.tailoredFor && (
                      <div className="flex items-center gap-1.5 mt-1.5 mb-3">
                        <Shuffle className="text-primary-container/60 flex-shrink-0" size={11} />
                        <p className="text-[11px] text-primary-container/70 italic">{q.tailoredFor}</p>
                      </div>
                    )}
                    {!q.tailoredFor && <div className="mb-3" />}
                    <div className="mb-3 p-3 bg-surface-container-low rounded-lg border-l-2 border-outline-variant/30">
                      <p className="text-[10px] text-outline uppercase font-bold mb-1">Respuesta esperada (referencia para HM):</p>
                      <p className="text-xs text-on-surface-variant italic leading-relaxed">{q.expectedAnswer}</p>
                    </div>
                    <textarea value={q.candidateAnswer} onChange={(e) => handleHmCandidateAnswer(q.id, e.target.value)} className="w-full bg-surface-container-low border-none rounded-xl p-4 text-sm focus:ring-2 focus:ring-primary-container transition-all resize-none" placeholder="Escribe la respuesta del candidato a esta pregunta técnica..." rows={3} />
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="flex justify-center mt-8">
            <button onClick={handleHmEvaluate} disabled={!hmAnsweredAll || isHmEvaluating} className={`flex items-center gap-3 px-10 py-4 rounded-xl font-black uppercase tracking-widest text-sm transition-all shadow-lg ${hmAnsweredAll && !isHmEvaluating ? 'bg-primary-container text-white hover:opacity-90 cursor-pointer' : 'bg-surface-container-high text-outline cursor-not-allowed'}`}>
              {isHmEvaluating ? (<><Loader2 className="animate-spin" size={20} />Evaluando con IA...</>) : (<><BarChart3 size={20} />Evaluar Entrevista Técnica</>)}
            </button>
          </div>

          {/* HM Match result */}
          {hmMatchScore !== null && (
            <div className="bg-surface-container-lowest p-8 rounded-2xl shadow-lg mt-8">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-6">
                  <div className="relative w-28 h-28 flex items-center justify-center">
                    <svg className="w-full h-full transform -rotate-90">
                      <circle className="text-surface-container-high" cx="56" cy="56" fill="transparent" r="48" stroke="currentColor" strokeWidth="8" />
                      <circle className={hmMatchScore >= 70 ? 'text-secondary' : 'text-error'} cx="56" cy="56" fill="transparent" r="48" stroke="currentColor" strokeDasharray="301" strokeDashoffset={301 - (301 * hmMatchScore) / 100} strokeWidth="8" strokeLinecap="round" />
                    </svg>
                    <span className={`absolute font-headline font-black text-3xl ${hmMatchScore >= 70 ? 'text-secondary' : 'text-error'}`}>{hmMatchScore}%</span>
                  </div>
                  <div>
                    <h3 className="font-headline text-2xl font-bold text-on-surface">Resultado Técnico: {interviewCandidate.name}</h3>
                    <div className="flex items-center gap-3 mt-1 mb-2">
                      <span className="text-xs text-on-surface-variant">CV: <strong>{interviewCandidate.matchScore}%</strong></span>
                      <span className="text-outline">→</span>
                      <span className="text-xs text-on-surface-variant">RH: <strong>{matchScore}%</strong></span>
                      <span className="text-outline">→</span>
                      <span className="text-xs text-secondary font-bold">HM: <strong>{hmMatchScore}%</strong></span>
                    </div>
                    <p className="text-sm text-on-surface-variant">
                      {hmMatchScore >= 80 ? 'Candidato fuerte técnicamente. Altamente recomendado.' : hmMatchScore >= 65 ? 'Sólido. Algunas brechas técnicas manejables con onboarding.' : 'Brechas técnicas significativas. Requiere evaluación adicional.'}
                    </p>
                  </div>
                </div>
                <div className="flex flex-col items-end gap-3">
                  <div className="flex items-center gap-2">
                    <CheckCircle2 className={hmMatchScore >= 70 ? 'text-secondary' : 'text-error'} size={20} />
                    <span className={`text-sm font-bold ${hmMatchScore >= 70 ? 'text-secondary' : 'text-error'}`}>
                      {hmMatchScore >= 80 ? 'Contratar' : hmMatchScore >= 65 ? 'Considerar Oferta' : 'No Continuar'}
                    </span>
                  </div>
                  <div className="flex items-center gap-1 text-on-surface-variant">
                    <TrendingUp size={14} />
                    <span className="text-[10px] font-bold uppercase">Score final: {Math.round((interviewCandidate.matchScore + (matchScore ?? 0) + hmMatchScore) / 3)}%</span>
                  </div>
                </div>
              </div>
            </div>
          )}
        </section>
      )}

      {/* ── PAGE NAVIGATION (HR only) ── */}
      {activeRole === 'hr' && (
        <div className="flex items-center justify-between mt-10 pt-6 border-t border-outline-variant/20">
          <div>
            {currentStepIndex > 0 && (
              <button onClick={() => setCurrentStep(HR_STEPS[currentStepIndex - 1].key)} className="flex items-center gap-2 px-6 py-3 rounded-xl font-bold text-sm text-on-surface-variant hover:bg-surface-container-low transition-all">
                <ChevronLeft size={18} />{HR_STEPS[currentStepIndex - 1].label}
              </button>
            )}
          </div>
          <div>
            {currentStep === 'input' && !generated && (
              <button onClick={handleGenerate} disabled={!canGenerate || isGenerating} className={`flex items-center gap-3 px-8 py-3 rounded-xl font-bold text-sm transition-all shadow-lg ${canGenerate && !isGenerating ? 'bg-primary-container text-white hover:opacity-90 cursor-pointer' : 'bg-surface-container-high text-outline cursor-not-allowed'}`}>
                {isGenerating ? (<><Loader2 className="animate-spin" size={18} />Procesando...</>) : (<><Sparkles size={18} />Generar con IA</>)}
              </button>
            )}
            {currentStep === 'input' && generated && (
              <button onClick={() => setCurrentStep('generated')} className="flex items-center gap-2 px-6 py-3 rounded-xl font-bold text-sm bg-primary-container text-white hover:opacity-90 transition-all">
                Siguiente<ChevronRight size={18} />
              </button>
            )}
            {currentStep === 'generated' && (
              <button onClick={() => { if (cvCandidates.length === 0) setCvCandidates(MOCK_CV_CANDIDATES); setCurrentStep('screening'); }} className="flex items-center gap-2 px-6 py-3 rounded-xl font-bold text-sm bg-primary-container text-white hover:opacity-90 transition-all">
                Screening CVs<ChevronRight size={18} />
              </button>
            )}
            {currentStep === 'screening' && approvedCandidates.length > 0 && (
              <button onClick={() => { if (!selectedCandidate) handleSelectCandidate(approvedCandidates[0].id); else setCurrentStep('interview'); }} className="flex items-center gap-2 px-6 py-3 rounded-xl font-bold text-sm bg-primary-container text-white hover:opacity-90 transition-all">
                Entrevista RH<ChevronRight size={18} />
              </button>
            )}
            {currentStep === 'interview' && hrDecision === 'continue' && (
              <button onClick={() => setCurrentStep('hm-interview')} className="flex items-center gap-2 px-6 py-3 rounded-xl font-bold text-sm bg-primary-container text-white hover:opacity-90 transition-all">
                Entrevista HM<ChevronRight size={18} />
              </button>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

